# MYSQL DB PROPERTIES
spring:
  datasource:
    url: jdbc:mysql://mysql/test
    username: testuser
    password: testuser@123
    driver-class-name: com.mysql.cj.jdbc.Driver

# POSTGRES DB PROPERTIES    
#spring:
#  datasource:
#    url: jdbc:postgresql://postgres/testdb
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true