version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
    - RABBITMQ_DEFAULT_USER= user
    - RABBITMQ_DEFAULT_PASS= user
    - RABBITMQ_DEFAULT_VHOST= rabbitmq-vhost
    volumes:
    - rabbitmq_data:/etc/rabbitmq/
    - rabbitmq_data:/var/lib/rabbitmq/
    - rabbitmq_data:/var/log/rabbitmq/
    ports:
    - 5672:5672
    - 15672:15672
  redis:
    image: redis
    container_name: redis
    environment:
    - REDIS_REPLICATION_MODE= master
    - REDIS_PASSWORD=password
    - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
    - 6379:6379
    volumes:
    - redis_data:/redis/data
  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
    - 7474:7474
    - 7687:7687
    volumes:
    - neo4j_data:/data
    - neo4j_data:/logs
    - neo4j_data:/plugins
    - neo4j_data:/import
    environment:
      NEO4J_AUTH: neo4j/pass
volumes:
  rabbitmq_data: null
  redis_data: null
  neo4j_data: null