version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
    - RABBITMQ_DEFAULT_USER= user
    - RABBITMQ_DEFAULT_PASS= user
    - RABBITMQ_DEFAULT_VHOST= rabbitmq-vhost
    volumes:
    - rabbitmq-data:/etc/rabbitmq/
    - rabbitmq-data:/var/lib/rabbitmq/
    - rabbitmq-data:/var/log/rabbitmq/
    ports:
    - 5672:5672
    - 15672:15672
volumes:
  rabbitmq-data: null